name: Release

on:
  workflow_run:
    workflows: ["CI"]
    branches: [main]
    types:
      - completed

jobs:
  publish-draft-release:
    name: Draft
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set git credentials
        run: |
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git config user.name "${{ github.actor }}"

      - name: Install Node
        uses: volta-cli/action@v1

      - name: Restore cached dependencies
        uses: actions/cache@v2
        id: cache
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm install

      - name: Verify build
        run: npm run ci:build

      - name: Update release branch
        run: npm run ci:release-draft

      - name: Create/update GitHub release
        uses: actions/github-script@v2
        with:
          script: |
            const publishDraftRelease = require(`${process.env.GITHUB_WORKSPACE}/scripts/github/publish-draft-release.js`)
            publishDraftRelease({ github, context })
