name: Publish Release

on:
  release:
    types: [published]

jobs:
  publish-release:
    name: Publish release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: 'main'

      - name: Set git credentials
        run: |
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git config user.name "${{ github.actor }}"

      - name: Publish release to 'main'
        run: |
          git rebase $(git branch --all --contains ${{ github.ref }})
          git push
