name: Release

on:
  push:
    branches:
      - master

jobs:
  update_release_draft:
    name: Draft Release
    runs-on: ubuntu-latest
    steps:
      # Drafts your next Release notes as Pull Requests are merged into "master"
      - name: Release Drafter
        uses: release-drafter/release-drafter@v5.11.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
